baseURL: http://www.sharats.me/
languageCode: en-us
title: "The Sharat's"
theme: serene

disqusShortname: sharats-me
googleAnalytics: UA-105705354-1
enableRobotsTXT: true

Paginate: 6
rssLimit: 10

pygmentsCodeFences: true
pygmentsUseClasses: true

author:
  name: Shrikant Sharat Kandula
  email: shrikantsharat.k@gmail.com
  facebook: sharat87
  linkedin: sharat87
  github: sharat87
  twitter: sharat87
  stackoverflow: 151048

menu:
  main:
    - name: Blog
      url: /posts/
      weight: 10
    - name: Labs
      url: /labs/
      weight: 20
    - name: Résumé
      url: /shrikant-sharat-kandula-resume.pdf
      weight: 30
    - name: RSS
      url: /posts/index.xml
      weight: 40
    - name: About
      url: /about/
      weight: 50


params:
  postProcess:
    - re: '<p>(TODO:?)'
      to: '<p style="color:red">$1'
    - re: '<p>(Note:?)'
      to: '<p><span class=note>$1</span>'
