name = "serene"
description = "a distraction-free hugo theme, based on nofancy"
license = "MIT"
licenselink = "http://opensource.org/licenses/MIT"
homepage = "http://sharats.me"
tags = ["blog", "personal", "clean", "simple", "white"]
features = ["distraction-free", "black-and-white"]
min_version=0.26

[author]
    name = "Shrikant Sharat Kandula"
    homepage = "http://sharats.me"
